export { OutOfServiceBedCreatePage } from './outOfServiceBedCreate'
export { OutOfServiceBedShowPage } from './outOfServiceBedShow'
export { OutOfServiceBedListPage } from './outOfServiceBedList'
export { OutOfServiceBedIndexPage } from './outOfServiceBedIndex'
export { OutOfServiceBedUpdatePage } from './outOfServiceBedUpdate'
export { OutOfServiceBedCancelPage } from './outOfServiceBedCancel'
export { OutOfServiceBedPremisesIndexPage } from './outOfServiceBedPremisesIndex'
