import { faker } from '@faker-js/faker'
import { Factory } from 'fishery'
import { ApprovedPremisesBedSearchParameters as BedSearchParameters } from '../../@types/shared'
import { BedSearchParametersUi } from '../../@types/ui'
import { DateFormats } from '../../utils/dateUtils'

export default Factory.define<BedSearchParameters, unknown, BedSearchParametersUi>(() => ({
  durationDays: faker.datatype.number({ min: 1, max: 90 }),
  startDate: DateFormats.dateObjToIsoDate(faker.date.soon()),
  maxDistanceMiles: faker.datatype.number({ min: 1, max: 100 }),
  postcodeDistrict: 'SW1',
  requiredPremisesCharacteristics: faker.helpers.arrayElements([
    'isIAP',
    'isPIPE',
    'isESAP',
    'isSemiSpecialistMentalHealth',
    'isRecoveryFocussed',
    'isSuitableForVulnerable',
    'acceptsSexOffenders',
    'acceptsChildSexOffenders',
    'acceptsNonSexualChildOffenders',
    'acceptsHateCrimeOffenders',
    'isCatered',
    'hasWideStepFreeAccess',
    'hasWideAccessToCommunalAreas',
    'hasStepFreeAccessToCommunalAreas',
    'hasWheelChairAccessibleBathrooms',
    'hasLift',
    'hasTactileFlooring',
    'hasBrailleSignage',
    'hasHearingLoop',
    'additionalRestrictions',
  ]),
  requiredRoomCharacteristics: faker.helpers.arrayElements([
    'IsGroundFloor',
    'isFullyFm',
    'hasCrib7Bedding',
    'hasEnsuite',
    'hasWashbasin',
    'hasShower',
    'hasSmokeDetector',
    'isTopFloorVulnerable',
    'isGroundFloorNrOffice',
    'hasNearbySprinkler',
    'isArsonSuitable',
    'isArsonDesignated',
    'hasArsonInsuranceConditions',
    'isSuitedForSexOffenders',
    'hasEnSuite',
    'isWheelchairAccessible',
    'hasWideDoor',
    'hasStepFreeAccess',
    'hasFixedMobilityAids',
    'hasFixedHearingLoop',
    'hasTurningSpace',
    'hasCallForAssistance',
    'isWheelchairDesignated',
    'isStepFreeDesignated',
  ]),
}))
