#!/bin/sh

# script/generate-types: Generates typescript types from the OpenApi spec in the API repo

set -e

cd "$(dirname "$0")/.."

echo "==> Generating types..."

npx openapi-typescript-codegen -i https://raw.githubusercontent.com/ministryofjustice/hmpps-approved-premises-api/main/src/main/resources/static/api.yml -o ./server/@types/api -c axios --exportServices false --exportCore false --useUnionTypes true

echo "==> Renaming the declaration file..."

mv ./server/@types/api/index.ts ./server/@types/api/index.d.ts


