#!/bin/sh

# script/generate-types: Generates typescript types from the OpenApi spec in the API repo

set -e

cd "$(dirname "$0")/.."

if [ -z "$1" ]; then
  branch="main"
else
  branch=$1
fi

echo "==> Generating types for $branch branch..."

npx openapi-typescript-codegen -i "https://raw.githubusercontent.com/ministryofjustice/hmpps-approved-premises-api/$branch/src/main/resources/static/codegen/built-api-spec.yml" -o ./server/@types/shared --exportServices false --exportCore false --useUnionTypes true
npx openapi-typescript-codegen -i "https://raw.githubusercontent.com/ministryofjustice/hmpps-approved-premises-api/$branch/src/main/resources/static/codegen/built-cas1-api-spec.yml" -o ./server/@types/shared --exportServices false --exportCore false --useUnionTypes true

echo "==> Renaming the declaration file..."

mv ./server/@types/shared/index.ts ./server/@types/shared/index.d.ts

echo "==> Copying roles to permissions mapping..."

curl -o ./server/utils/users/data/rolesToPermissions.json -s "https://raw.githubusercontent.com/ministryofjustice/hmpps-approved-premises-api/$branch/src/main/resources/static/codegen/built-cas1-roles.json"
