name: Deploy to test

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker_build:
    name: Build docker image from hmpps-github-actions
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@3481c2cefa046f0c700952082dcb21b91d96c348 # v2.14.8
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      push: true
      docker_multiplatform: false
      tag_latest: false

  deploy_test:
    name: Deploy to the test environment
    needs:
      - docker_build
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@3481c2cefa046f0c700952082dcb21b91d96c348 # v2.14.8
    secrets: inherit
    with:
      environment: 'test'
      app_version: '${{ needs.docker_build.outputs.app_version }}'
